version: "3.9"
services:
  app:
    build: .
    working_dir: /app
    command: >
      bash -c "bundle install &&
               bundle exec rake assets:precompile &&
               bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db

    db:
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: toppin_dev
