default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db # Cambia a 'db' si usas Docker
  port: 3306
  username: root
  password: password
  reconnect: true

development:
  <<: *default
  database: toppin_dev

test:
  <<: *default
  database: rails_toppin_test

production:
  <<: *default
  database: rails_toppin_production
  username: production_user
  password: production_password