default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  database: "<%= ENV.fetch('DATABASE_NAME') %>"
  host: "<%= ENV.fetch('DATABASE_HOST') %>"
  port: "<%= ENV.fetch('DATABASE_PORT') %>"
  username: "<%= ENV.fetch('DATABASE_USER') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

development:
  <<: *default

test:
  <<: *default
  database: rails_toppin_test

production:
  <<: *default
  database: rails_toppin_production
  username: "<%= ENV.fetch('DATABASE_USER', 'production_user') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'production_password') %>"
