class TranslateInterestsToEnglish < ActiveRecord::Migration[6.0]
  def up
    translations = {
      'Música' => 'music',
      'Pop' => 'pop',
      'Rock' => 'rock',
      'Indie' => 'indie',
      'Electrónica' => 'electronic',
      'Clásica' => 'classical',
      'Jazz' => 'jazz',
      'Hip Hop' => 'hip_hop',
      'Rap' => 'rap',
      'R&B' => 'r&b',
      'Soul' => 'soul',
      'Folk' => 'folk',
      'Metal' => 'metal',
      'Punk' => 'punk',
      'Reggae' => 'reggae',
      'Ska' => 'ska',
      'Blues' => 'blues',
      'Country' => 'country',
      'Reggaeton' => 'reggaeton',
      'Salsa' => 'salsa',
      'Bachata' => 'bachata',
      'Cumbia' => 'cumbia',
      'K-Pop' => 'k_pop',
      'J-Pop' => 'j_pop',
      'World Music' => 'world_music',
      'Alternativa' => 'alternative',
      'Años 80' => '80s',
      'Años 90' => '90s',
      'Festivales de música' => 'music_festivals',
      'Conciertos' => 'concerts',
      'Películas y Series' => 'movies_and_series',
      'Acción' => 'action',
      'Aventura' => 'adventure',
      'Comedia' => 'comedy',
      'Drama' => 'drama',
      'Ciencia Ficción' => 'science_fiction',
      'Fantasía' => 'fantasy',
      'Terror' => 'horror',
      'Suspense' => 'thriller',
      'Thriller' => 'thriller',
      'Misterio' => 'mystery',
      'Romance' => 'romance',
      'Documentales' => 'documentaries',
      'Anime' => 'anime',
      'Series de TV' => 'tv_series',
      'Miniseries' => 'miniseries',
      'Cine clásico' => 'classic_cinema',
      'Cine de autor' => 'auteur_cinema',
      'Cine independiente' => 'independent_cinema',
      'Películas de culto' => 'cult_movies',
      'Stand-up comedy' => 'stand_up_comedy',
      'Reality Shows' => 'reality_shows',
      'Deportes y Fitness' => 'sports_and_fitness',
      'Fútbol' => 'soccer',
      'Baloncesto' => 'basketball',
      'Tenis' => 'tennis',
      'Pádel' => 'padel',
      'Running' => 'running',
      'Ciclismo' => 'cycling',
      'Natación' => 'swimming',
      'Yoga' => 'yoga',
      'Pilates' => 'pilates',
      'Gimnasio' => 'gym',
      'Gym' => 'gym',
      'Crossfit' => 'crossfit',
      'Entrenamiento funcional' => 'functional_training',
      'Senderismo' => 'hiking',
      'Hiking' => 'hiking',
      'Montañismo' => 'mountaineering',
      'Escalada' => 'climbing',
      'Esquí' => 'skiing',
      'Snowboard' => 'snowboarding',
      'Surf' => 'surfing',
      'Skateboarding' => 'skateboarding',
      'Artes Marciales' => 'martial_arts',
      'Boxeo' => 'boxing',
      'Baile' => 'dancing',
      'Voleibol' => 'volleyball',
      'Golf' => 'golf',
      'Rugby' => 'rugby',
      'Fórmula 1' => 'formula_1',
      'MotoGP' => 'motogp',
      'eSports' => 'esports',
      'Hobbies e Intereses' => 'hobbies_and_interests',
      'Lectura' => 'reading',
      'Escritura' => 'writing',
      'Viajes' => 'travel',
      'Fotografía' => 'photography',
      'Cocina' => 'cooking',
      'Repostería' => 'baking',
      'Jardinería' => 'gardening',
      'Pintura' => 'painting',
      'Dibujo' => 'drawing',
      'Escultura' => 'sculpture',
      'Manualidades' => 'diy_crafts',
      'DIY' => 'diy',
      'Bricolaje' => 'diy',
      'Videojuegos' => 'video_games',
      'Juegos de mesa' => 'board_games',
      'Puzzles' => 'puzzles',
      'Aprender idiomas' => 'learning_languages',
      'Tocar instrumentos musicales' => 'playing_instruments',
      'Cantar' => 'singing',
      'Bailar' => 'dancing_hobby',
      'Teatro' => 'theater',
      'Cine' => 'cinema',
      'Tecnología' => 'technology',
      'Programación' => 'programming',
      'Ciencia' => 'science',
      'Historia' => 'history',
      'Filosofía' => 'philosophy',
      'Astronomía' => 'astronomy',
      'Moda' => 'fashion',
      'Decoración de interiores' => 'interior_design',
      'Tatuajes' => 'tattoos',
      'Piercings' => 'piercings',
      'Coleccionismo' => 'collecting',
      'Voluntariado' => 'volunteering',
      'Astrología' => 'astrology',
      'Tarot' => 'tarot',
      'Criptomonedas' => 'cryptocurrencies',
      'Inversiones' => 'investing',
      'Comida y Bebida' => 'food_and_drinks'
    }

    translations.each do |spanish, english|
      execute <<-SQL
        UPDATE interests SET name = '#{english}' WHERE name = '#{spanish}';
      SQL
      
      # También actualizar el campo interest_name en user_interests si existe
      if column_exists?(:user_interests, :interest_name)
        execute <<-SQL
          UPDATE user_interests SET interest_name = '#{english}' WHERE interest_name = '#{spanish}';
        SQL
      end
      
      # También actualizar el campo name en user_main_interests
      if column_exists?(:user_main_interests, :name)
        execute <<-SQL
          UPDATE user_main_interests SET name = '#{english}' WHERE name = '#{spanish}';
        SQL
      end
    end
  end

  def down
    # Reversión si necesitas volver al español
    translations = {
      'music' => 'Música',
      'pop' => 'Pop',
      'rock' => 'Rock',
      'indie' => 'Indie',
      'electronic' => 'Electrónica',
      'classical' => 'Clásica',
      'jazz' => 'Jazz',
      'hip_hop' => 'Hip Hop',
      'rap' => 'Rap',
      'r&b' => 'R&B',
      'soul' => 'Soul',
      'folk' => 'Folk',
      'metal' => 'Metal',
      'punk' => 'Punk',
      'reggae' => 'Reggae',
      'ska' => 'Ska',
      'blues' => 'Blues',
      'country' => 'Country',
      'reggaeton' => 'Reggaeton',
      'salsa' => 'Salsa',
      'bachata' => 'Bachata',
      'cumbia' => 'Cumbia',
      'k_pop' => 'K-Pop',
      'j_pop' => 'J-Pop',
      'world_music' => 'World Music',
      'alternative' => 'Alternativa',
      '80s' => 'Años 80',
      '90s' => 'Años 90',
      'music_festivals' => 'Festivales de música',
      'concerts' => 'Conciertos',
      'movies_and_series' => 'Películas y Series',
      'action' => 'Acción',
      'adventure' => 'Aventura',
      'comedy' => 'Comedia',
      'drama' => 'Drama',
      'science_fiction' => 'Ciencia Ficción',
      'fantasy' => 'Fantasía',
      'horror' => 'Terror',
      'thriller' => 'Thriller',
      'mystery' => 'Misterio',
      'romance' => 'Romance',
      'documentaries' => 'Documentales',
      'anime' => 'Anime',
      'tv_series' => 'Series de TV',
      'miniseries' => 'Miniseries',
      'classic_cinema' => 'Cine clásico',
      'auteur_cinema' => 'Cine de autor',
      'independent_cinema' => 'Cine independiente',
      'cult_movies' => 'Películas de culto',
      'stand_up_comedy' => 'Stand-up comedy',
      'reality_shows' => 'Reality Shows',
      'sports_and_fitness' => 'Deportes y Fitness',
      'soccer' => 'Fútbol',
      'basketball' => 'Baloncesto',
      'tennis' => 'Tenis',
      'padel' => 'Pádel',
      'running' => 'Running',
      'cycling' => 'Ciclismo',
      'swimming' => 'Natación',
      'yoga' => 'Yoga',
      'pilates' => 'Pilates',
      'gym' => 'Gimnasio',
      'crossfit' => 'Crossfit',
      'functional_training' => 'Entrenamiento funcional',
      'hiking' => 'Senderismo',
      'mountaineering' => 'Montañismo',
      'climbing' => 'Escalada',
      'skiing' => 'Esquí',
      'snowboarding' => 'Snowboard',
      'surfing' => 'Surf',
      'skateboarding' => 'Skateboarding',
      'martial_arts' => 'Artes Marciales',
      'boxing' => 'Boxeo',
      'dancing' => 'Baile',
      'volleyball' => 'Voleibol',
      'golf' => 'Golf',
      'rugby' => 'Rugby',
      'formula_1' => 'Fórmula 1',
      'motogp' => 'MotoGP',
      'esports' => 'eSports',
      'hobbies_and_interests' => 'Hobbies e Intereses',
      'reading' => 'Lectura',
      'writing' => 'Escritura',
      'travel' => 'Viajes',
      'photography' => 'Fotografía',
      'cooking' => 'Cocina',
      'baking' => 'Repostería',
      'gardening' => 'Jardinería',
      'painting' => 'Pintura',
      'drawing' => 'Dibujo',
      'sculpture' => 'Escultura',
      'diy_crafts' => 'Manualidades',
      'diy' => 'Bricolaje',
      'video_games' => 'Videojuegos',
      'board_games' => 'Juegos de mesa',
      'puzzles' => 'Puzzles',
      'learning_languages' => 'Aprender idiomas',
      'playing_instruments' => 'Tocar instrumentos musicales',
      'singing' => 'Cantar',
      'dancing_hobby' => 'Bailar',
      'theater' => 'Teatro',
      'cinema' => 'Cine',
      'technology' => 'Tecnología',
      'programming' => 'Programación',
      'science' => 'Ciencia',
      'history' => 'Historia',
      'philosophy' => 'Filosofía',
      'astronomy' => 'Astronomía',
      'fashion' => 'Moda',
      'interior_design' => 'Decoración de interiores',
      'tattoos' => 'Tatuajes',
      'piercings' => 'Piercings',
      'collecting' => 'Coleccionismo',
      'volunteering' => 'Voluntariado',
      'astrology' => 'Astrología',
      'tarot' => 'Tarot',
      'cryptocurrencies' => 'Criptomonedas',
      'investing' => 'Inversiones',
      'food_and_drinks' => 'Comida y Bebida'
    }

    translations.each do |english, spanish|
      execute <<-SQL
        UPDATE interests SET name = '#{spanish}' WHERE name = '#{english}';
      SQL
      
      if column_exists?(:user_interests, :interest_name)
        execute <<-SQL
          UPDATE user_interests SET interest_name = '#{spanish}' WHERE interest_name = '#{english}';
        SQL
      end
      
      if column_exists?(:user_main_interests, :name)
        execute <<-SQL
          UPDATE user_main_interests SET name = '#{spanish}' WHERE name = '#{english}';
        SQL
      end
    end
  end
end
